options(repos = c(CRAN = "https://cloud.r-project.org"))
install.packages("devtools") # added installation of this package for installing rnaturalearthhires from GH
install.packages("tidyverse")
install.packages("targets")
install.packages("dataRetrieval") # this now requires curl >= 7.0.0 so I removed the curl installation
install.packages("httr2")
install.packages("tools")
install.packages("sf")
install.packages("xml2")
install.packages("leaflet")
install.packages("RColorBrewer")
install.packages("htmlwidgets")
install.packages("rnaturalearth")
devtools::install_github("ropensci/rnaturalearthhires")
install.packages("svglite")
install.packages("chromote")
install.packages("pandoc")
install.packages("visNetwork")
install.packages("htmltools")
install.packages("magick")
install.packages("IRkernel")
