install.packages("tidyverse")
install.packages("targets")
install.packages("dataRetrieval")
install.packages("httr2")
install.packages("tools")
install.packages("sf")
install.packages("xml2")
install.packages("leaflet")
install.packages("RColorBrewer")
install.packages("htmlwidgets")
install.packages("tigris")
install.packages("svglite")
install.packages("chromote")
install.packages("pandoc")
install.packages("visNetwork") 
devtools::install_version("curl", "7.0.0")
