#' @title Plot Hydrographs with NWS Flood Stage
#' @description This function creates a set of hydrographs (time series plots) of USGS gage height data, faceted by site, and overlays the corresponding National Weather Service (NWS) minor flood stage as a horizontal line. It returns a `ggplot` object.
#'
#' @param nwis_nws_data A combined tibble (`data.frame`) containing the NWIS stage data, NWS flood stage, site ID, and site name. This is typically the output from the `p2_stage_flooding_data` target.
#'
#' @return A **`ggplot` object** representing the hydrograph plot.
#'
plot_hydrographs <- function(nwis_nws_data){
  
  # Create the base plot with 'time' on the x-axis
  m <- ggplot(nwis_nws_data, aes(x = time)) + 
    # Plot gage height as a blue line
    geom_line(aes(y = value, color = "Gage height")) +
    # Plot 'flood_stage' as a red line on the same plot
    geom_line(aes(y = flood_stage, color = "National Weather Service Floodstage")) +
    # Facet the plot by site ID and name, with one column and free y-scales
    facet_wrap(~ paste0(monitoring_location_id, ", ", monitoring_location_name), ncol = 1, scales = "free") +
    # Manually define colors and names for the legend
    scale_color_manual(
      name = "Legend",
      values = c(
        "Gage height" = "blue",
        "National Weather Service Floodstage" = "red"
      )
    ) +
    # Set the y-axis label
    labs(
      y = "Gage height, feet"
    ) +
    # Format the x-axis date labels
    scale_x_date(date_labels = "%d-%b-%Y") +
    # Use bw theme (so the x and y axes still show up)
    theme_bw() +
    # Customize theme elements
    theme(
      strip.text = element_text(face = "bold", size = 10),
      legend.position = "bottom",
      legend.title = element_blank()
    )
  
  return(m)
  
}

#' @title Save Hydrographs Plot as SVG
#' @description This function takes a `ggplot` object of hydrographs and saves it to a specified file path as an SVG file using `ggsave`.
#'
#' @param plot_object A **`ggplot` object** generated by `plot_hydrographs` or a similar plotting function.
#' @param out_dir A character string for the **directory path** where the SVG plot will be saved.
#' @param out_file A character string for the **filename** of the SVG plot to be saved (e.g., `"hydrographs.svg"`).
#' @param width An optional numeric value specifying the width of the plot in the units specified by `units`. Defaults to `10`.
#' @param height An optional numeric value specifying the height of the plot in the units specified by `units`. Defaults to `8`.
#' @param units A character string specifying the units for `width` and `height`. Defaults to `"in"` (inches).
#'
#' @return A **character string** representing the full file path to the saved SVG hydrograph plot.
#'
save_hydrographs <- function(plot_object, out_dir, out_file, width = 10, height = 8, units = "in") {
  
  # Combine the directory and filename to create the full output path
  out_path <- file.path(out_dir, out_file)
  
  # Save the plot object to the specified full path
  ggsave(out_path, plot = plot_object, width = width, height = height, units = units)
  
  print(paste0('Hydrograph plots saved to ', out_path))
  
  return(out_path)
  
}
